const icons = {
  WELCOME_BG: require("../images/angkor.jpg"),
  PUC: require("../images/puc.png"),
  AVATAR: require("../images/avatar.jpeg"),
  IMAGE_BG_TEST: require("../images/landingtravel.png"),
  WING: require("../images/wing.png"),
  SLID1: require("../images/slide1.png"),
  SLID2: require("../images/slide2.png"),
  SLID3: require("../images/slide3.jpg"),
  SLID4: require("../images/slide4.png"),
  REGISTER_TESTING: require("../images/lightbulbIdea.png"),
  // ENGLISH_PROGRAM: require("../images/product.png"),
  // ACADEMIC_PROGRAM: require("../images/sunglasses.png"),
  // PSIS_PROGRAM: require("../images/book.png"),
  SPEL_PROGRAM: require("../images/headphones.png"),
  // IELT_PROGRAM: require("../images/fountain_pen.png"),
  SHORT_PROGRAM: require("../images/book.png"),
  EVENTS_PROGRAM: require("../images/sunglasses.png"),
  FACULTY_ART: require("../images/image1.jpg"),
  FACULTY_BUSSINESS: require("../images/image2.jpg"),
  FACULTY_LAW: require("../images/image3.jpg"),
  FACULTY_EDUCATION: require("../images/image4.jpg"),
  FACULTY_SCIENCES: require("../images/image5.jpg"),
  FACULTY_MEDIA: require("../images/image6.jpg"),
  FACULTY_SOCAIL: require("../images/image7.jpg"),
  FACULTY_MENAGEMENT: require("../images/image8.jpg"),
  FACULTY_DESIGN: require("../images/image9.jpg"),

  ENG_IMAGE1: require('../images/eng1.jpg'),
  ENG_IMAGE2: require('../images/eng2.jpg'),
  ENG_IMAGE3: require('../images/eng3.jpg'),
  ENG_IMAGE4: require('../images/eng4.jpg'),
  ENG_IMAGE5: require('../images/eng5.jpg'),
  ENG_IMAGE6: require('../images/eng6.jpg'),
  ENG_IMAGE7: require('../images/eng7.jpg'),
  ENG_IMAGE8: require('../images/eng8.jpg'),
  ENG_IMAGE9: require('../images/eng9.jpg'),

  UNDER_CONSTRUCTION:require('../images/under-construction.png'),
  SIGN_IN_COVER:require('../images/login-image.png'),

  
};

module.exports = icons;
