# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'kpfoundation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kpfoundation

  # target 'kpfoundation-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # target 'kpfoundationTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Functions'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'

end

# target 'kpfoundation-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for kpfoundation-tvOS

#   target 'kpfoundation-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
